name: ui_kit
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  pin_code_fields: ^8.0.1
  data_table_2: ^2.5.18
  flutter_screenutil: ^5.9.3
  toastification: ^3.0.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  image_network: ^2.6.0
  fl_chart: ^0.71.0
  # flutter_pdfview: ^1.4.0+1
  syncfusion_flutter_pdfviewer: ^29.1.41
  flutter:
    sdk: flutter
  core:
    git:
      url: https://github.com/Ctrt-Entreprise/core.git
      ref: main
  intl: ^0.19.0
  percent_indicator: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/flags/
    - assets/payment_images/
    - assets/images/
    - assets/icons/